{% set version = "1.1.4" %}

package:
  name: pcmsolver
  version: {{ version }}

source:
  git_url: git@github.com:PCMSolver/pcmsolver.git      # [linux]
  git_url: https://github.com/PCMSolver/pcmsolver.git  # [osx]
  git_tag: v{{ version }}

build:
  number: 0
  binary_relocation: true
  skip: true                                           # [win]

requirements:
  build:
    - boost >=1.53     # [osx]
    - cmake >=2.8.10
    - gcc              # [osx]    # build w/ gcc, gfortran
    - zlib
  run:
    - libgcc           # [osx]    # link libgfortran, libquadmath, libstdc++, libgcc_s
    - zlib                        # link libz

test:
  commands:
    # Verify library.
    - test -f $PREFIX/lib/libpcm.so     # [linux]
    - test -f $PREFIX/lib/libpcm.dylib  # [osx]

about:
  home: http://pcmsolver.readthedocs.org/en/latest/
  license: GNU Lesser General Public License v3 (LGPLv3)
  summary: "Polarizable Continuum Model API"
  readme: README.md

